### ISSUE TITLE
Request updated FD data from Kevin and re-run code to check for issues @MandyKarnauskas-NOAA

### ISSUE THREAD

**Issue by CarissaGervasi-NOAA** [Gulf-IEA/Caribbean-ESR#14]

**Comment by CarissaGervasi-NOAA** [comment]
Mandy emailed Caribbean folks, recent data pull is in a google drive folder

**Comment by MandyKarnauskas-NOAA** [comment]
Finished updating all fishery-dependent indicators with recent data pull.  
Results look similar except for disturbance indicator which came out differently.  Need to go back and check.
