### ISSUE TITLE
Efficacy of management indicator

### ISSUE THREAD

**Issue by CarissaGervasi-NOAA** [Gulf-IEA/Caribbean-ESR#22]
Maria Lopez - Team lead of Caribbean branch in SERO

Trying to capture governance aspects in the Caribbean report. What is the percentage of species we have informative catch limits for? 

Where do we get the full species list? In the [FMPs](https://www.fisheries.noaa.gov/southeast/sustainable-fisheries/sustainable-fisheries-caribbean)

ABC control rule tier - 4a is low vulnerability 4b is high vulnerability

Spiny lobster recently changed to tier 3 for all 3 islands
triggerfish complex in PR will change to tier 3 - not final yet - should be in like 4 months
queen triggerfish is managed separately - in the USVI (STT and STX) will be changes to tier 3 but still in the process - might not happen until later this year 

In the TOC, 2.4 is the action that pertains to table 2.4.1 - ABC control rule. 
chapter 5 is the management plan 5.13.6 is the ABC control rule
Appendix G is the process Table G5 is the table we want that lists the 

63 species of fish plus spiny lobster, queen conch, etc in PR
43 species of fish plus others in STX
another list in STT

species lists are different in each region

prior to the island based plans, when we managed at the Caribbean level but ACLs were 

4a and 4b designation is new

2012 ACLs when they were put in place there was no control rule. Or it wasn't called that. No stock assessments for anything. 

Used to have 4 FMPs - reef fish, corals, spiny lobster, queen conch
when MSA was reauthoraized required to set ACLS
first species we did ACLs on were either overfished or undergoing overfishing - snappers, queen conch, etc. 2010 ACL amendment set ACLs for those species
2011 - rest of the species were not undergoing overfishing. Hundreds of species - set ACLs
repealed the species based plans when moved to island based management
eliminated species not in need of management and added some others

Action 4 of the FMP tells how they used to manage things - 2.4.1, 2.4.2

used to have something called sustainable yield level?

Adyan is a good source of info since she worked on the assessments

**Comment by CarissaGervasi-NOAA** [comment]
Table from Maria: https://drive.google.com/file/d/1agM_DJ9VJ4eadZXG4O5KCvbRSUHS0pbg/view?usp=sharing

**Comment by CarissaGervasi-NOAA** [comment]
@MandyKarnauskas-NOAA I am still a little confused on what we want to do for this indicator. Are we just presenting the number or percentage of species/stocks with each Tier designation - 4a, 4b, or 3 (only spiny lobster for now). I guess this could just be like a 3-panel bar graph?

**Comment by MandyKarnauskas-NOAA** [comment]
a bar graph would be ideal to show the different categories but Tier 3 would be invisible.  Let's just do the % of species in the FMPs that are managed under Tier 3 control rules (that will be zero since 2011 and then like 0.5% as of last year)

**Comment by CarissaGervasi-NOAA** [comment]
👍

**Comment by CarissaGervasi-NOAA** [comment]
Indicator completed.
